### ISSUE TITLE
No ProxyHandler class found

### ISSUE THREAD

**Issue by abhi041980** [aesteve/vertx-load-balancer#2]
Hi Aesteve, 

              I dont see a ProxyHandler class in the github for the load balancer code you have provided.

thanks 
Regards
Kits

**Comment by aesteve** [comment]
Hello @abhi041980 this repository is 8 years old and targets Vert.x 3.2.1 which did not have a `ProxyHandler` class at the time.

I suggest you use: https://github.com/vert-x3/vertx-examples where examples are maintained and up to date with the latest Vert.x version.

I am going to archive this repository so that it's clear it was an old experiment I did on a week-end 8 years ago.
